name: CI

on:
  push:

jobs:
  test:
    name: Lint, Type Check and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Instalar dependencias # de pyproject.toml y uv.lock
        run: uv sync

      - name: Revisar Formato (Ruff)
        run: uv run ruff format --check .

      - name: Revisar Sintaxis (Ruff Linter)
        run: uv run ruff check .

      - name: Revisar Tipado Estático (Mypy)
        run: uv run mypy src/ tests/

      - name: Ejecutar Pruebas (Pytest)
        run: uv run pytest
